eureka:
  client:
    registerWithEureka: 'true'
    fetchRegistry: 'true'
    serviceUrl:
      defaultZone: 'http://ems-registry-service:9090/eureka/'
  instance:
    hostname: ems-registry-service
 
  
