eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: defaultZone: http://eureka-0.eureka.default.svc.cluster.local:eureka:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:eureka:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:eureka:8761/eureka
  instance:
    prefer-ip-address: false
 
  
