eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.152.183.254:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: configserver
 
  
