eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ems-registry-service:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: configserver
 
  
